export type {
  OpenSearchClusterInfo,
  OpenSearchDocumentHit,
  OpenSearchExportIndicesRequest,
  OpenSearchExportIndicesResponse,
  OpenSearchHttpMethod,
  OpenSearchImportIndicesRequest,
  OpenSearchImportIndicesResponse,
  OpenSearchIndexInfo,
  OpenSearchIndexMeta,
  OpenSearchRawRequest,
  OpenSearchRawResponse,
  OpenSearchResponse,
  OpenSearchSearchRequest,
  OpenSearchSearchResult,
  OpenSearchVoidResponse,
} from '../../shared/types/opensearch';
